#!/bin/sh

echo "Building for Unix systems..."
go build -o releases/ohmyscan main.go

echo "Building for Windows-x32 system..."
GOOS=windows GOARCH=386 go build -o releases/ohmyscan-x32.exe main.go

echo "Building for Windows-x64 system ..."
GOOS=windows GOARCH=386 go build -o releases/ohmyscan-x64.exe main.go